feat: allow setting vm firmware
terra-farm/terraform-provider-virtualbox pull request #129
Opened 2022-01-07 07:50 UTC by ghouscht

Hi,
As stated in https://github.com/terra-farm/go-virtualbox/pull/28  I need this to create VMs which only support EFI boot, which is now working with these changes.
Thank you,
Thomas

2022-01-07 15:19 UTC, VoyTechnology requested changes
The changes you added look good, but what is missing is adding the ability to read the firmware back in ` resourceVMRead` function.

```go
if err = d.Set("firmware", vm.Firmware); err != nil {
	return diag.Errorf("can't set firmware: %v", err)
}
```

2022-01-07 15:20 UTC, VoyTechnology commented on virtualbox/resource_vm.go
> +			},
If there are only two possible options, perhaps we should add a validator.

2022-01-07 15:21 UTC, VoyTechnology commented on virtualbox/resource_vm.go
> +				Description: "Firmware of the vm, can either be BIOS or EFI",
What happens if the user provides the values in lower case, like `bios` or `efi`?

2022-01-07 15:56 UTC, ghouscht commented
> The changes you added look good, but what is missing is adding the ability to read the firmware back in ` resourceVMRead` function.
> 
> ```go
> if err = d.Set("firmware", vm.Firmware); err != nil {
> 	return diag.Errorf("can't set firmware: %v", err)
> }
> ```

Uh, good catch, I missed that, sorry. Also done with the latest changes.

2022-01-29 10:04 UTC, ghouscht commented
HI @VoyTechnology,
Any chance to get this merged in the near future?
Thanks, Thomas

2023-04-24 14:08 UTC, closed without merging